### PR TITLE
Hover validation

### PR DESCRIPTION
**Pull request by felixfbecker**
https://github.com/sourcegraph/issues/issues/138

I don't know how to deploy this.

### CODE REVIEW

**Comment by sqs** [comment]
The PR LGTM. But I am adding better dev/publish instructions now, and my hope is that they are good enough for you to follow yourself (so I spread the knowledge here). Will post back here when they are ready for you to follow then merge+publish.

**Comment by sqs** [comment]
@felixfbecker I am going to merge and deploy this to get this fixed sooner. Can you take a look at the updated README and see if it would have successfully helped you deploy this yourself? https://github.com/sourcegraph/sourcegraph-langserver-http#readme

**Comment by sqs** [comment]
I missed a problem when merging this. Fixed: https://github.com/sourcegraph/sourcegraph-langserver-http/commit/5c7de4868cc84d24810fcf4cc1ee63e38d9c1442

**Comment by felixfbecker** [comment]
> an you take a look at the updated README and see if it would have successfully helped you deploy this yourself? 

One thing I am confused about is that this repo seems to publish itself as a private npm package (which makes the badges show errors). Are we referencing that from the main repo to bundle the extension into the web app? This seems to contradict the text though:

> To release a new version (which will immediately be used by all Sourcegraph instances), you need to bundle and upload that file.

Also, regarding "which will immediately be used by all Sourcegraph instances", isn't that dangerous? Shouldn't we bake them into the frontend like we do with the Phabricator bundle?

Could this repo (and other extensions) get automatic deployments?

**Comment by sqs** [comment]
It doesn’t publish itself anymore. That was a mistake.

Re: dangerous, yes (from a backcompat POV).

Automatic publishing of the extension to Sourcegraph would be great for the extension authoring experience in general.

**Comment by felixfbecker** [comment]
So what do you think of doing it like with the Phab bundle? I.e. _do_ publish to npm, bake into frontend, get updates from Renovate.

> Automatic publishing of the extension to Sourcegraph would be great for the extension authoring experience in general.

If the publish step is just a shell command it could be done with the https://github.com/semantic-release/exec plugin. The package.json could be updated by using the npm plugin for `prepare`. But it would probably be nice to have a dedicated plugin like there is for VS Code extensions: https://github.com/raix/semantic-release-vsce (that should be easy to fork)

**Comment by felixfbecker** [comment]
What is the versioning story for extensions?
- Do we support versions at all, and are older versions still served?
- Are they immutable?
- Do we enforce version numbers to match semver?
- Do we support prereleases / previews? Release channels?

**Comment by sqs** [comment]
https://github.com/sourcegraph/sourcegraph-langserver-http/pull/4#issuecomment-419127248 sounds good.

As for the other questions re: versioning story, I can answer based on the current state but it is not the intended end state, so don't take this to be normative. We have a field called `version` in the DB `registry_extension_releases` but don't do anything with it yet. We also have an unused DB field called `tag` for `release`, `beta`, etc. Releases are immutable given a release ID (which is a sequential number, such as `10` in https://sourcegraph.com/-/static/extension/10.js?bo5pbfeaor40), but nothing is read/written/enforced about versions.

I think that being casual about releases (not exposing version/tag, not enforcing semver, etc.) is fine for now, but we'll find out quickly what is needed as we get more people writing extensions. This would be a great area for you to help with next iteration.

**Pull request merged**
